### ISSUE TITLE
I can't open it with yarn

### ISSUE THREAD

**Issue by kali100x** [nawangwe/opensea-whitelabel-website-template#11]
I did everything to install but all time give internal server error. Please help.
Thanks.
![image](https://user-images.githubusercontent.com/97807071/150136410-888ece00-6c06-41c5-aa17-c1ea398fb114.jpeg)
![image](https://user-images.githubusercontent.com/97807071/150136461-55be25bb-6ac9-41d7-bc8d-8dad0fbd5de5.jpeg)![image](https://user-images.githubusercontent.com/97807071/150136474-ab25b250-fdab-452c-a597-f0848cf9e830.jpeg)

**Comment by allenchuang** [comment]
same here.. what seems to be the issue?? is it because of nextjs?

**Comment by nawangwe** [comment]
Could also be related to [this](https://github.com/ProjectOpenSea/opensea-js/issues/401)

**Comment by allenchuang** [comment]
gotcha- solved it with API key

**Comment by allenchuang** [comment]
you could add `OPEN_SEA_API` in the env config and then just read that key wherever you call OpenSeaport like so:
```

  const seaport = new OpenSeaPort(provider, {
    networkName: Network.Main,
    apiKey: process.env.OPEN_SEA_API,
  });

```

**Comment by nawangwe** [comment]
@allenchuang great to hear that solved it. I'll update the repo and readme to include this, as well as update the repo for any other issues.
