### ISSUE TITLE
Getting "Error: Failed to validate buy order parameters. Make sure you're on the right network!" when buying assets

### ISSUE THREAD

**Issue by allenchuang** [nawangwe/opensea-whitelabel-website-template#12]
I've been trying to buy asset by invoking fulfillOrder in `[tokenid].js` but I'm getting error:

Error: Failed to validate buy order parameters. Make sure you're on the right network!

seaport creation code:

```
  const seaport = new OpenSeaPort(provider, {
    networkName: Network.Main, // <-- mainnet
    apiKey: process.env.OPEN_SEA_API, // valid API Key
  });

```

in `initiatePurchase` fulfillOrder code:

```
await seaport.fulfillOrder({
            order: order,
            accountAddress: address,
});
```

What could be the cause?

**Comment by allenchuang** [comment]
i figred out why this is the case- i think it is because of the JSON parsing that happens in `getServerSideProps`:
```const asset = JSON.parse(JSON.stringify(assetResponse));```
 causing some property type mismatch when doing the validation on OpenseaPort side. 
 
 @nawangwe do you have a work around for this? so far i've just moved the `getOrder` call directly inside `initiatePurchase` but now seeing CORS issue 🤦🏻‍♂️

**Comment by nawangwe** [comment]
@allenchuang i'll get around to this today, it seems that the opensea is library and api require frequent monitoring and I haven't maintained this repo in a while.

**Comment by allenchuang** [comment]
also- from their API it seems that you no longer need to use `getAsset` you can use `getOrder` function and pass in the returned object to `fulfillOrder` as updated in their README.  Sorry for dumping all this info on you if it's too much, just trying to help the best i can :D

**Comment by nawangwe** [comment]
No worries @allenchuang I really appreciate the help! As I'm currently tied down with other projects. Feel free to contribute as well. I'll definitely begin maintaining this on a regular basis.

**Comment by allenchuang** [comment]
sure! If I get to it before you do i'll file a PR for your approval. Cheers! 🙌🏼

**Comment by allenchuang** [comment]
update: `opensea-js` is ridiculous to work with- after several hours of digging, i realized that they are rehauling their API but didn't update their SDKs. the `orderToJSON` and `orderFromJSON` don't even work in conjunction.

`orderToJSON` returns camelCaseProps while `orderToJSON` expects snake_case_props 🤦🏻‍♂️ 

Based on the little information on OS dev blogs, I think its best to migrate over to ^2.0.2 for now.

https://opensea.io/blog/developers/wyvern-2-3-developer-upgrade-guide/
https://docs.opensea.io/changelog

**Comment by nawangwe** [comment]
@allenchuang noted, seems like it's no small task, do let me know if and what you're working on, because I intend to attend to it as early as today :)

**Comment by allenchuang** [comment]
so far i'm working on getting the buy function to work again, but i keep getting errors submitting the transaction, haven't got a working version for PR yet.

What i've done so far
- added OpenSea API key support (could submit this as a PR first since this is independent of the other changes)

I'm a bit confused because using fetch order API from https://docs.opensea.io/reference/retrieving-orders returns `snake_case_props` but using `getAsset` or `getOrder` returns `camelCaseProps`

so i'm not sure if the way to go is:
- use fetch in `getStateFromProps`
- parse it with `orderToJSON`
- then unparse it using `orderFromJSON` and pass it to the SDK `OpenSeaPort` for actually submitting buy order

testing it rn, will let you know

**Comment by allenchuang** [comment]
i tried to push a new branch for the API support but i don't have access to the repo, any chance you can give me contributor access?

**Comment by nawangwe** [comment]
I added you as a collaborator @allenchuang, you can check your email. However, make a PR to dev, I made a few small changes that do a bit of error handling. Could be wrong though, so feel free to overwrite the minimal changes eg. versions and error handling implementation

**Comment by nawangwe** [comment]
never mind, will merge master's changes to dev

**Comment by allenchuang** [comment]
update: i've tried using the fetch approach- but it's giving me the same error as the title states again...
`Failed to validate buy order parameters. Make sure you're on the right network!`

i'm a bit stumped. i can open [WIP] PR and add some comments, you can pull and take a look at teh changes i've done so far, perhaps you can make better progress!

**Comment by nawangwe** [comment]
noted @allenchuang
